apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  annotations:
    tekton.dev/docker-0: https://${REGISTRY_HOSTNAME}
type: kubernetes.io/basic-auth
stringData:
  username: userX
  password: ${STUDENT_PASSWORD}
