apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  annotations:
    tekton.dev/docker-0: https://${REGISTRY_HOSTNAME}
    tekton.dev/docker-1: https://registry-quay-quay.apps.cluster-YYYYY.YYYYY.sandboxZZZZ.opentlc.com:443
type: kubernetes.io/basic-auth
stringData:
  username: userX
  password: redhat123
