= 1. Introduction
include::_attributes.adoc[]
:experimental:

== 1.1. Goal of the Workshop
The goal of this lab is to access the benefits of using containers by providing a hands-on experience in building a container image and using podman to create and run containers. This labs also aims to showcase the integration of CI/CD processes to automate certain tasks.  

== 1.2. Workshop Environment

=== 1.2.1. Confirm Your Username!
Look in the box at the top of your screen. Is your username set already? If so it will look like this:

alreadyset
If your username is properly set, then you can move on. If not, in the above box, enter the user ID you were assigned like this:

setuser
This will customize the links and copy/paste code for this workshop. If you accidentally type the wrong username, just update your username in the URL parameters (e.g. `1-introduction.html?USERID=%USERID%` )

Important
You have to use an unique username (e.g. %USERID%) while you’re running the hands-on labs. For example, you need to deploy applications to your own project (e.g. retail-%USERID%).

=== 1.2.2. OpenShift Cluster
Your OpenShift cluster is already configured with everything you need. Here are the details:

`Gitea` to host the source code repositories

`OpenShift` Virtualization to ultimately run the migrated Oracle VM

`Migration Toolkit for Virtualization` to facilitate the migration of the Oracle VM to Red Hat OpenShift Container Platform

`OpenShift GitOps` to manage the deployed services using a GitOps approach through ArgoCD

`OpenShift Pipelines` to build the customer application from source code and deploy to the retail project using GitOps

`Migration Toolkit for Applications` to help modernize the customer service.

=== 1.2.2. OpenShift Dev Spaces 
Built on the open source Eclipse Che project, Red Hat OpenShift Dev Spaces uses Kubernetes and containers to provide developers and other IT team members with a consistent, secure, and zero-configuration development environment.

Your Dev Spaces environment is already configured on your OpenShift cluster and will be making use of Visual Studio Code Server. 

VSCode is already deployed in the OpenShift cluster for you to use as your IDE. This means you don’t need to install and configure anything on your system. This makes it easy to change source code and configuration files in the cloned repository.

To get started, access the `VS Code server instance` and log in using the following password.

Password: {openshift-password}

=== 1.2.2. Quay Regsitry

Red Hat Quay is a distributed and highly available container image registry. It provides a single and resilient content repository for delivering containerized software to development and production across OpenShift clusters.

Quay is already deployed and configured in the OpenShift cluster for you. To access your Quay registry, log in using the following credentials. 

xxxxxxx
