#!/bin/bash

cd `dirname $0`
BASE=`pwd`
cd - >> /dev/null

source ${BASE}/../config.sh

oc delete -n $WORKSHOPPER_PROJ bc,build,is,istag -l build=workshopper
oc delete -n $WORKSHOPPER_PROJ deploy,svc,route -l app=workshopper

exit 0
