#!/bin/bash

cd `dirname $0`
BASE=`pwd`
cd - >> /dev/null

source ${BASE}/../config.sh

oc delete -n $ANTORA_PROJ bc,build,is,istag -l build=antora
oc delete -n $ANTORA_PROJ deploy,svc,route -l app=workshop-content

exit 0
