#!/bin/bash

cd `dirname $0`
BASE=`pwd`
cd - >> /dev/null

source ${BASE}/../config.sh

u=1 \
&& \
while [ $u -le $NUM_USERS ]; do
  USER="user${u}"
  echo "deleting project for ${USER}..."

  oc delete project ${USER} 2>/dev/null

  u=$(( $u + 1 ))
done

exit 0
