#!/bin/bash

cd `dirname $0`
BASE=`pwd`
cd - >> /dev/null

source ${BASE}/../config.sh

function ensure_set {
	local varName="$1"
	if [ -z "${!varName}" ]; then
		echo "$varName is not set"
		exit 1
	fi
}

ensure_set STUDENT_COUNT
ensure_set STUDENT_PASSWORD

which htpasswd >/dev/null 2>/dev/null
if [ $? -ne 0 ]; then
  echo "htpasswd executable does not exist"
  exit 1
fi

which base64 >/dev/null 2>/dev/null
if [ $? -ne 0 ]; then
  echo "base64 executable does not exist"
  exit 1
fi

rm -f /tmp/htpasswd

oc get secret htpasswd -n openshift-config >/dev/null 2>/dev/null
if [ $? -ne 0 ]; then
  echo "could not get htpasswd secret"
  exit 1
fi

oc get secret htpasswd -n openshift-config -o jsonpath='{.data.htpasswd}' \
| \
base64 -d \
| \
grep admin \
> /tmp/htpasswd

if [ $? -ne 0 ]; then
  echo "could not extract admin user from htpasswd"
  exit 1
fi

set -e

u=1 \
&& \
while [ $u -le $STUDENT_COUNT ]; do
  USER="user${u}"
  echo "creating password for ${USER}..."

  htpasswd -B -b /tmp/htpasswd $USER $STUDENT_PASSWORD

  u=$(( $u + 1))
done

oc set data -n openshift-config secret/htpasswd --from-file=htpasswd=/tmp/htpasswd
rm -f /tmp/htpasswd
oc delete -n openshift-authentication po -l app=oauth-openshift
