#!/bin/bash

set -e

echo "Deploy Quay Operator..."
cat <<EOF | oc apply -f -
apiVersion: v1
kind: Namespace
metadata:
 labels:
   openshift.io/cluster-monitoring: "true"
 name: quay-enterprise
spec: {}
EOF

cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
 name: quay-operator
 namespace: openshift-operators
spec:
 channel: "stable-3.9"
 installPlanApproval: Automatic
 name: quay-operator
 source: redhat-operators  # <-- Modify the name of the redhat-operators catalogsource if not default
 sourceNamespace: openshift-marketplace
EOF

sleep 20
while [ `oc get csv -n quay-enterprise | grep quay | awk '{print $7}'` != "Succeeded" ]
do
  echo "Wait for Quay Operator to be deployed..."
  sleep 5
done

cat <<EOF | oc apply -f -
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: registry
  namespace: quay-enterprise
EOF

echo "Get Quay Registry Endpoint"
while ! [ `oc get quayregistry -n quay-enterprise registry -o jsonpath="{.status.registryEndpoint}"` ]
do
  echo "Wait for Quay Registry Endpoint"
  sleep 15
done

oc get quayregistry -n quay-enterprise registry -o jsonpath="{.status.registryEndpoint}"
echo -e "\n"

while [ `oc get pod -n quay-enterprise | grep -v Running | grep -v Completed | grep -v NAME | head -1 | awk '{print $1}'` ]
do
  echo "Wait for Quay to be deployed..."
  sleep 15
done

echo "Red Hat Quay Deployed"
