apiVersion: v1
kind: Namespace
metadata:
  name: remote-installer
spec: {}
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: remote-installer
  namespace: remote-installer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: remote-installer
  namespace: remote-installer
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: remote-installer
  name: remote-installer
  namespace: remote-installer
spec:
  template:
    spec:
      serviceAccountName: remote-installer
      containers:
      - name: remote-installer
        image: "ghcr.io/rhsgsa/hybrid-cloud-installer:latest"
        env:
        - name: HOME
          value: /home/install
        command:
        - /bin/bash
        - "-c"
        - |
          git config --global user.email "installer@example.com"
          git config --global user.name "Remote Installer"

          git clone https://github.com/rhsgsa/cicd-lab.git

          cd cicd-lab

          if [ -f "../custom-config/config.sh" ]; then
            cp ../custom-config/config.sh .
          fi

          make install

          echo "installation completed"

        #volumeMounts:
        #- name: config
        #  mountPath: "/home/install/custom-config"
        #  readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            cpu: "0.5"
            memory: 1Gi
          requests:
            cpu: "0.5"
            memory: 1Gi
      #volumes:
      #- name: config
      #  configMap:
      #    name: remote-installer-config
      restartPolicy: Never
  backoffLimit: 2
