apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workshopper
  name: workshopper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshopper
  strategy: {}
  template:
    metadata:
      labels:
        app: workshopper
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/infra/workshopper
        name: workshopper
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: workshopper
  name: workshopper
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: workshopper
status:
  loadBalancer: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: workshopper
  name: workshopper
spec:
  port:
    targetPort: 8080
  to:
    name: workshopper
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
status: {}
